# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 15:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_no', models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('[0-9]')])),
                ('store_address1', models.CharField(max_length=100, verbose_name='Store Address Line 1')),
                ('store_address2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Store Address Line 2')),
                ('store_postal', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('[0-9]')], verbose_name='Store Postal Code')),
                ('store_contact_no', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(code='nomatch', message='8 digit phone number only', regex='^([0-9]{8})$')], verbose_name='Store Contact No')),
                ('store_district_area', models.CharField(max_length=2, verbose_name='Store District and Area')),
                ('assigned_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.Drivers', verbose_name='Driver Responsible')),
            ],
        ),
        migrations.CreateModel(
            name='StoreRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date of Request')),
                ('request_fulfilled_date', models.DateTimeField(blank=True, null=True, verbose_name='Request Fulfilled Date')),
                ('request_invoice_no', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Invoice No')),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.Drivers', verbose_name='Assigned Driver')),
                ('request_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed By')),
                ('request_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('requesting_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s11.Store', verbose_name='Requesting Store')),
            ],
        ),
    ]
