# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 15:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=75, verbose_name='Driver Name (Passport/IC)')),
                ('nick_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Driver Nick Name')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator('[0-9]')], verbose_name='Contact Number')),
                ('wechat_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Driver WeChat ID')),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Postal_Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_areas', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('[0-9]')])),
                ('region_names', models.CharField(max_length=200, verbose_name='Postal Code Region Names')),
            ],
            options={
                'ordering': ('postal_areas',),
            },
        ),
        migrations.AddField(
            model_name='drivers',
            name='delivery_areas',
            field=models.ManyToManyField(to='drivers.Postal_Areas', verbose_name='Regions Served'),
        ),
        migrations.AddField(
            model_name='drivers',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.Designation', verbose_name='Driver Role'),
        ),
    ]
