# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_drivers_delivery_restrictions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ('priority',)},
        ),
        migrations.AddField(
            model_name='designation',
            name='priority',
            field=models.CharField(blank=True, choices=[('1', 'Route Drivers'), ('2', ''), ('3', 'Half-Agent'), ('4', ''), ('5', 'Reserve Drivers'), ('6', ''), ('7', 'Agent'), ('8', ''), ('9', 'Unresponsive'), ('10', '')], max_length=2, null=True),
        ),
    ]
