# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_auto_20170901_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivers',
            options={'ordering': ('designation', 'full_name')},
        ),
    ]
