# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_auto_20170902_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='delivery_areas',
            field=models.ManyToManyField(blank=True, to='drivers.Postal_Areas', verbose_name='Regions Served'),
        ),
    ]
