# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 17:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_details',
            name='billing_postal',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('[0-9]')], verbose_name='Billing Postal Code'),
        ),
    ]
