# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 08:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0003_customer_customer_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True, verbose_name='Price')),
                ('customer_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='Customer')),
                ('item_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_product_qty', models.IntegerField(verbose_name='Order Qty')),
                ('order_product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Price')),
                ('additional_details', models.CharField(max_length=200, verbose_name='Additional Details')),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='Orders_Adhoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Delivery Date')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Creation Date')),
                ('confirmation_status', models.BooleanField(default=False, verbose_name='Confirmations Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='Customer')),
            ],
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders_Adhoc', verbose_name='Order Reference'),
        ),
    ]
