# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='additional_details',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Additional Details'),
        ),
    ]
