# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote_products',
            name='quote_product_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Product Description'),
        ),
    ]
